### ISSUE TITLE
配置之后仍在报警告

### ISSUE THREAD

**Issue by qq31311137** [meowtec/vite-plugin-import#1]
`
plugins: [
	svgPlugin(),
	createImportPlugin([
		{
			libraryName: 'ant-design-vue',
			style: true,
		},
	]),
],
`

**Comment by meowtec** [comment]
贴一下 log

**Comment by qq31311137** [comment]
@meowtec 我使用的是 vite1

**Comment by meowtec** [comment]
> @meowtec 我使用的是 vite1

具体什么警告描述一下
