### ISSUE TITLE
dep:antd:8 You are using a whole package of antd

### ISSUE THREAD

**Issue by g0shed** [meowtec/vite-plugin-import#2]
still getting the You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size. message, is this normal?

**Comment by meowtec** [comment]
`vite-plugin-import` only work in production mode. You should check your bundle size to see if it is normal.

**Comment by meowtec** [comment]
BTW, if you are using the higher version antd (`antd@3` `antd@4`), you would not need `vite-plugin-import` or `babel-plugin-import`

**Comment by mindreframer** [comment]
I have just tried it with `antd@4` in the included example, indeed the final size seems to drop: 

```
npm run build

> vite-plugin-import-example@0.0.0 build /Users/roman/go/src/github.com/happycodrz/bettrjob/tmp/vite-plugin-import/examples/antd
> vite build

'default' is imported from external module 'vite-plugin-import' but never used
building for production...
✓ 997 modules transformed.
dist/index.html                  0.35kb
dist/assets/index.0e39eadc.js    0.67kb / brotli: 0.35kb
dist/assets/vendor.e39be9f4.js   93.09kb / brotli: 26.67kb
```

So, `93kb`. 

With the `vite-plugin-import` the size increases and I see errors / warnings: 

```
$ npm run build

> vite-plugin-import-example@0.0.0 build /Users/roman/go/src/github.com/happycodrz/bettrjob/tmp/vite-plugin-import/examples/antd
> vite build

building for production...
✓ 309 modules transformed.
warnings when minifying css:
Invalid character(s) 'getAugmentedNamespace from "commonjsHelpers.js"; export default getAugmentedNamespace(style);' at 2205:435. Ignoring.
Invalid selector 'import * as style from "/Users/roman/go/src/github.com/happycodrz/bettrjob/tmp/vite-plugin-import/examples/antd/node_modules/antd/lib/style/index.css"; import' at 2205:0. Ignoring.
Invalid selector 'getAugmentedNamespace from "commonjsHelpers.js"; export default getAugmentedNamespace(style);import * as style from "/Users/roman/go/src/github.com/happycodrz/bettrjob/tmp/vite-plugin-import/examples/antd/node_modules/antd/lib/switch/style/index.css"; import' at 2205:160. Ignoring.
dist/index.html                   0.41kb
dist/assets/index.25dbb6ef.js     0.67kb / brotli: 0.36kb
dist/assets/vendor.3db50a62.css   41.97kb / brotli: 3.87kb
dist/assets/vendor.82282d12.js    259.63kb / brotli: 67.67kb
```

So yeah, when should this plugin be used at all?

**Comment by meowtec** [comment]
> antd

This plugin is only for some library that do not really support tree shacking. Usually some primary, unpopular or old libraries.

If you are using antd, you will not need this.

How to decide whether to use this:

If the doc of some library tell you to use `babel-plugin-import`, you may need use this plugin or [@rollup/plugin-babel](https://github.com/vitejs/vite/issues/1617#issuecomment-764203943) + `babel-plugin-import`. The first one is a little faster. But you need another babel plugin, you should use the second way.

I have change the example from `antd` to `antd-mobile`, that will not cause confusing.

Those warnings (Invalid character) seems like some bug of vite's internal css plugin.

**Comment by mindreframer** [comment]
@meowtec thanks for the quick response! 

OK, I assume this plugin is not suitable for `antd` and will try to figure out another way to reduce the bundle size for antd with vite.js. 

Have a good weekend!
