### ISSUE TITLE
能支持ts类型的文件后缀名？

### ISSUE THREAD

**Issue by oopsman** [meowtec/vite-plugin-import#7]
```
transform(code, id) {
      if (!/\.(js|jsx|vue)$/.test(id)) return;   //支持ts文件类型？
      return {
        code: transformSrcCode(code, transformOptions(plgOptions), viteConfig),
        map: null,
      };
}
```
项目大都是ts类型文件了   会导致不能引入相应的文件
//main.ts 
import { ElDialog,ElTable } from 'element-plus';

**Comment by meowtec** [comment]
Demo 就是 TS 的，我实际开发的项目也是 TS 的，都没有问题。
「 会导致不能引入相应的文件」具体表现是什么？发一个能复现问题的仓库例子出来看看？

**Comment by oopsman** [comment]
b

> Demo 就是 TS 的，我实际开发的项目也是 TS 的，都没有问题。
> 「 会导致不能引入相应的文件」具体表现是什么？发一个能复现问题的仓库例子出来看看？

不好意思   搜错插件名称了  vite-plugin-babel-import 这个插件不支持ts
