### ISSUE TITLE
重复plugin

### ISSUE THREAD

**Issue by j-xzy** [meowtec/vite-plugin-import#8]
https://github.com/meowtec/vite-plugin-import/blob/e9860cfac50b4b52be4501f6b90eef140f576008/src/index.ts#L46

建议加一个idx
babelImportPluginOptions.map((mod,idx) => ['import', mod, `import-${idx}`])

**Comment by meowtec** [comment]
这里应该是写错了，本来应该是以 `import-${mod.libraryName}` 为唯一 ID 的

**Comment by j-xzy** [comment]
修复发布下？

**Comment by meowtec** [comment]
已发布 v0.4.0
