### ISSUE TITLE
不生效

### ISSUE THREAD

**Issue by gujiwuqing** [meowtec/vite-plugin-import#9]
![image](https://user-images.githubusercontent.com/44566835/124413675-b316c400-dd83-11eb-9f06-d2d1b437e364.png)
![image](https://user-images.githubusercontent.com/44566835/124413703-be69ef80-dd83-11eb-9c47-337a80cb9c03.png)
![image](https://user-images.githubusercontent.com/44566835/124413730-cc1f7500-dd83-11eb-99a5-26ee2d0885b4.png)
因为这里不生效 所以提个问题 希望大佬能够看看

**Comment by meowtec** [comment]
AntD 版本？

**Comment by gujiwuqing** [comment]
> AntD 版本？

antd最新版本

**Comment by meowtec** [comment]
> > AntD 版本？
> 
> antd最新版本

高版本 antd 本来就支持 tree-shacking，不需要这个插件
